Fix Lib Path

diff --git a/.github/workflows/build_gstreamer.yml b/.github/workflows/build_gstreamer.yml
--- a/.github/workflows/build_gstreamer.yml
+++ b/.github/workflows/build_gstreamer.yml
@@ -105,6 +105,17 @@ jobs:
           meson compile -C builddir
           meson install -C builddir
 
+      - name: Fix LIB Path
+        run: |
+          cd /data/data/com.termux/files/usr/glibc
+          find . -type f -exec file {} + | grep -E ":.*ELF" | cut -d: -f1 | while read -r elf_file; do
+              echo "Patching $elf_file..."
+              patchelf --set-rpath "$LD_RPATH" --set-interpreter "$LD_FILE" "$elf_file" || {
+                  echo "Failed to patch $elf_file" >&2
+                  continue
+              }
+          done
+
       - name: Package glibc
         run: |
           cd /data/data/com.termux/files/usr/
